### PR TITLE
Add sportcoat for design feedback

### PR DESCRIPTION
**Pull request by graysonwright**
We should talk about this before you merge it in, but I think this will be
really cool if we can get it working

https://dashboard.heroku.com/apps/dischords/code/github
http://sportcoat.io/

### CODE REVIEW

**Comment by wrightmhw** [comment]
Alright. The first link, though... Ill go ahead and connect github to heroku?

**Comment by graysonwright** [comment]
yeah, what I'm thinking is that if you make a change to the design in a pull request, it'll spin up a new app for the code in the pull request. You can send a sportcoat link to the changes and get comments on them before you merge it in.

**Comment by wrightmhw** [comment]
sooo i might go ahead and merge?

**Comment by graysonwright** [comment]
aaahhh... yeah, sure. I don't think we'll be able to use the heroku pull request deploys, but I can at least use it to point things out on the site.

**Comment by wrightmhw** [comment]
Thanks, Gray!

**Pull request merged**
