### PR TITLE
Add a hound.yml to turn on JS and CSS style checks

### PR DESCRIPTION
**Pull request by graysonwright**

### CODE REVIEW

**Comment by graysonwright** [comment]
Don't merge this yet

**Comment by graysonwright** [comment]
ugh. terrible time for heroku to be down... https://status.heroku.com/

I want to make sure Hound comments on this PR, so we know if we have it set up correctly. So we can wait until heroku's back up, then try to add more bad code to see if it gets caught.

**Comment by graysonwright** [comment]
Hey, Michael! Looks like Hound is up and running.

I'll leave this up so you have a chance to take a look at how it works, but let me know and I'll fix the errors so you can merge this in.

**Comment by graysonwright** [comment]
Also, this: http://robots.thoughtbot.com/introducing-hound

**Comment by wrightmhw** [comment]
Gray, this looks great! Wow. That was way too easy :)

**Comment by graysonwright** [comment]
Cool! Good to merge!

By the way, you might want to merge things through the command line to avoid things like this in the commit history:
screenshot 2015-01-19 10 31 14
– thoughtbot wrote up our process on it, if you're interested: https://github.com/thoughtbot/guides/tree/master/protocol/git#merge

There's also good advice on that page for opening pull requests and getting comments on them.

**Pull request merged**
